# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '18.hafta-odev.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(386, 693)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 10, 141, 31))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(220, 20, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 50, 141, 31))
        self.label_2.setObjectName("label_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(220, 60, 113, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 90, 141, 31))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(40, 130, 141, 31))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(40, 170, 141, 31))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(40, 220, 141, 31))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(40, 260, 141, 31))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(40, 300, 141, 31))
        self.label_8.setObjectName("label_8")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(220, 180, 113, 20))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(220, 220, 113, 20))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_6.setGeometry(QtCore.QRect(220, 260, 113, 20))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_7.setGeometry(QtCore.QRect(220, 300, 113, 20))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(220, 90, 111, 41))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton.setGeometry(QtCore.QRect(10, 10, 51, 21))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_2.setGeometry(QtCore.QRect(70, 10, 81, 21))
        self.radioButton_2.setObjectName("radioButton_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(40, 370, 291, 192))
        self.textBrowser.setObjectName("textBrowser")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(80, 580, 251, 31))
        self.checkBox.setObjectName("checkBox")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(260, 630, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(150, 630, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(220, 130, 111, 41))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.radioButton_4 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_4.setGeometry(QtCore.QRect(10, 10, 81, 21))
        self.radioButton_4.setObjectName("radioButton_4")
        self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_3.setGeometry(QtCore.QRect(70, 10, 51, 21))
        self.radioButton_3.setObjectName("radioButton_3")
        self.commandLinkButton = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.commandLinkButton.setGeometry(QtCore.QRect(220, 330, 111, 41))
        self.commandLinkButton.setObjectName("commandLinkButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 386, 21))
        self.menubar.setObjectName("menubar")
        self.menuDeneme1 = QtWidgets.QMenu(self.menubar)
        self.menuDeneme1.setObjectName("menuDeneme1")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuDeneme1.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Adi:"))
        self.label_2.setText(_translate("MainWindow", "Soyadi:"))
        self.label_3.setText(_translate("MainWindow", "Cinsiyet:"))
        self.label_4.setText(_translate("MainWindow", "Medeni Durumu:"))
        self.label_5.setText(_translate("MainWindow", "Mail:"))
        self.label_6.setText(_translate("MainWindow", "Mail Tekrari:"))
        self.label_7.setText(_translate("MainWindow", "Pasword:"))
        self.label_8.setText(_translate("MainWindow", "Pasword Tekrari:"))
        self.radioButton.setText(_translate("MainWindow", "Erkek"))
        self.radioButton_2.setText(_translate("MainWindow", "Kiz"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:600; font-style:italic; color:#ff0000;\">Uyelik Sartlari Asagida belirtilmistir:</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe UI\'; font-size:7pt; font-weight:600; text-decoration: underline; color:#5500ff;\">Hotmail hesabı nasıl açılır?</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe UI\'; font-size:6pt; color:#333333;\"><br /></span><span style=\" font-family:\'Segoe UI\'; font-size:6pt; color:#333333; background-color:#ffffff;\">Dünya çapında en yaygın kullanılan e mail hizmetlerinden biri olan Hotmail\'in kolay kullanımı ve üstün özellikleri tercih sebebi oluyor. Hotmail hesabı nasıl açılır? Hotmail mail depolama aracı kullanım kolaylıkları neler? Outlook oturumu yönetme hakkında merak edilenler….</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe UI\'; font-size:6pt; color:#333333; background-color:#ffffff;\">Öncelikle Outlook hesap açma sayfası olan</span><a href=\"http://live.com/\"><span style=\" font-family:\'Segoe UI\'; font-size:6pt; text-decoration: underline; color:#126d91;\">https://login.live.com/</span></a><span style=\" font-family:\'Segoe UI\'; font-size:6pt; color:#333333;\"> gidin. Önünüze çıkan sayfadaki boşlukları doldurun. Alacağınız Hotmail adresi örnek olarak abc@hotmail.com şeklinde olacaktır. İkinci bölümde yer alan “hotmail.com&quot; isminin bir kaç alternatifi bulunmaktadır. Bunlar; outlook.com – outlook.com.tr – hotmail.com – hotmail.com.tr – windowslive.com. Seçim size kalmış. Bilindiği gibi Hotmail artık Outlook oldu ama değişen sadece tema oldu. Belirlediğiniz hotmail ismi eğer sistemde varsa Hotmail sizi uyaracak ve hatta size alternatif isimler önerecektir.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe UI\'; font-size:6pt; color:#333333; background-color:#ffffff;\">Outlook hesap açma işlemleri bu kadar basit. Şimdi siz de hemen bir Hotmail hesabı açın Outlook\'un size sunacağı üstün özellikleri ile mailleşin…</span></p></body></html>"))
        self.checkBox.setText(_translate("MainWindow", "Yukaridaki sartlari okudum ve kabul ediyorum."))
        self.pushButton.setText(_translate("MainWindow", "Kaydet"))
        self.pushButton_2.setText(_translate("MainWindow", "İptal"))
        self.radioButton_4.setText(_translate("MainWindow", "Bekar"))
        self.radioButton_3.setText(_translate("MainWindow", "Evli"))
        self.commandLinkButton.setText(_translate("MainWindow", "İlerle"))
        self.menuDeneme1.setTitle(_translate("MainWindow", "Deneme1"))
