# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Create_Account.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 666)
        font = QtGui.QFont()
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        MainWindow.setFont(font)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        MainWindow.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:0.897727 rgba(204, 255, 198, 255))")
        MainWindow.setDocumentMode(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.namebox = QtWidgets.QLineEdit(self.centralwidget)
        self.namebox.setGeometry(QtCore.QRect(300, 139, 161, 31))
        self.namebox.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.namebox.setObjectName("namebox")
        self.namebutton = QtWidgets.QLabel(self.centralwidget)
        self.namebutton.setEnabled(False)
        self.namebutton.setGeometry(QtCore.QRect(130, 140, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.namebutton.setFont(font)
        self.namebutton.setStyleSheet("background-color:rgb(205, 255, 247)")
        self.namebutton.setFrameShape(QtWidgets.QFrame.Box)
        self.namebutton.setTextFormat(QtCore.Qt.AutoText)
        self.namebutton.setObjectName("namebutton")
        self.userbox = QtWidgets.QLineEdit(self.centralwidget)
        self.userbox.setGeometry(QtCore.QRect(300, 99, 161, 31))
        self.userbox.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.userbox.setObjectName("userbox")
        self.createaccountbutton = QtWidgets.QPushButton(self.centralwidget)
        self.createaccountbutton.setEnabled(False)
        self.createaccountbutton.setGeometry(QtCore.QRect(130, 10, 331, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.createaccountbutton.setFont(font)
        self.createaccountbutton.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.createaccountbutton.setStyleSheet("background-color:rgb(205, 255, 247)")
        self.createaccountbutton.setObjectName("createaccountbutton")
        self.userbutton = QtWidgets.QLabel(self.centralwidget)
        self.userbutton.setEnabled(False)
        self.userbutton.setGeometry(QtCore.QRect(130, 100, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.userbutton.setFont(font)
        self.userbutton.setStyleSheet("background-color:rgb(205, 255, 247)")
        self.userbutton.setFrameShape(QtWidgets.QFrame.Box)
        self.userbutton.setTextFormat(QtCore.Qt.AutoText)
        self.userbutton.setObjectName("userbutton")
        self.signupbutton = QtWidgets.QPushButton(self.centralwidget)
        self.signupbutton.setGeometry(QtCore.QRect(220, 540, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.signupbutton.setFont(font)
        self.signupbutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.signupbutton.setStyleSheet("background-color:rgb(79, 255, 67)")
        self.signupbutton.setObjectName("signupbutton")
        self.surnamebox = QtWidgets.QLineEdit(self.centralwidget)
        self.surnamebox.setGeometry(QtCore.QRect(300, 179, 161, 31))
        self.surnamebox.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.surnamebox.setObjectName("surnamebox")
        self.surnamebutton = QtWidgets.QLabel(self.centralwidget)
        self.surnamebutton.setEnabled(False)
        self.surnamebutton.setGeometry(QtCore.QRect(130, 180, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.surnamebutton.setFont(font)
        self.surnamebutton.setStyleSheet("background-color:rgb(205, 255, 247)")
        self.surnamebutton.setFrameShape(QtWidgets.QFrame.Box)
        self.surnamebutton.setTextFormat(QtCore.Qt.AutoText)
        self.surnamebutton.setObjectName("surnamebutton")
        self.genderbutton = QtWidgets.QLabel(self.centralwidget)
        self.genderbutton.setEnabled(False)
        self.genderbutton.setGeometry(QtCore.QRect(130, 220, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.genderbutton.setFont(font)
        self.genderbutton.setStyleSheet("background-color:rgb(205, 255, 247)")
        self.genderbutton.setFrameShape(QtWidgets.QFrame.Box)
        self.genderbutton.setTextFormat(QtCore.Qt.AutoText)
        self.genderbutton.setObjectName("genderbutton")
        self.marriagebox = QtWidgets.QLineEdit(self.centralwidget)
        self.marriagebox.setGeometry(QtCore.QRect(300, 259, 161, 31))
        self.marriagebox.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.marriagebox.setObjectName("marriagebox")
        self.marriagebutton = QtWidgets.QLabel(self.centralwidget)
        self.marriagebutton.setEnabled(False)
        self.marriagebutton.setGeometry(QtCore.QRect(130, 260, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.marriagebutton.setFont(font)
        self.marriagebutton.setStyleSheet("background-color:rgb(205, 255, 247)")
        self.marriagebutton.setFrameShape(QtWidgets.QFrame.Box)
        self.marriagebutton.setTextFormat(QtCore.Qt.AutoText)
        self.marriagebutton.setObjectName("marriagebutton")
        self.emailbox = QtWidgets.QLineEdit(self.centralwidget)
        self.emailbox.setGeometry(QtCore.QRect(300, 299, 161, 31))
        self.emailbox.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.emailbox.setObjectName("emailbox")
        self.emailbutton = QtWidgets.QLabel(self.centralwidget)
        self.emailbutton.setEnabled(False)
        self.emailbutton.setGeometry(QtCore.QRect(130, 300, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.emailbutton.setFont(font)
        self.emailbutton.setStyleSheet("background-color:rgb(205, 255, 247)")
        self.emailbutton.setFrameShape(QtWidgets.QFrame.Box)
        self.emailbutton.setTextFormat(QtCore.Qt.AutoText)
        self.emailbutton.setObjectName("emailbutton")
        self.paswoordbox = QtWidgets.QLineEdit(self.centralwidget)
        self.paswoordbox.setGeometry(QtCore.QRect(300, 379, 161, 31))
        self.paswoordbox.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.paswoordbox.setObjectName("paswoordbox")
        self.paswoordbutton = QtWidgets.QLabel(self.centralwidget)
        self.paswoordbutton.setEnabled(False)
        self.paswoordbutton.setGeometry(QtCore.QRect(130, 380, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.paswoordbutton.setFont(font)
        self.paswoordbutton.setStyleSheet("background-color:rgb(205, 255, 247)")
        self.paswoordbutton.setFrameShape(QtWidgets.QFrame.Box)
        self.paswoordbutton.setTextFormat(QtCore.Qt.AutoText)
        self.paswoordbutton.setObjectName("paswoordbutton")
        self.confirmpaswoordbox = QtWidgets.QLineEdit(self.centralwidget)
        self.confirmpaswoordbox.setGeometry(QtCore.QRect(300, 419, 161, 31))
        self.confirmpaswoordbox.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.confirmpaswoordbox.setObjectName("confirmpaswoordbox")
        self.confirmpaswoordbutton = QtWidgets.QLabel(self.centralwidget)
        self.confirmpaswoordbutton.setEnabled(False)
        self.confirmpaswoordbutton.setGeometry(QtCore.QRect(130, 420, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.confirmpaswoordbutton.setFont(font)
        self.confirmpaswoordbutton.setStyleSheet("background-color:rgb(205, 255, 247)")
        self.confirmpaswoordbutton.setFrameShape(QtWidgets.QFrame.Box)
        self.confirmpaswoordbutton.setTextFormat(QtCore.Qt.AutoText)
        self.confirmpaswoordbutton.setObjectName("confirmpaswoordbutton")
        self.confirmemailbox = QtWidgets.QLineEdit(self.centralwidget)
        self.confirmemailbox.setGeometry(QtCore.QRect(300, 339, 161, 31))
        self.confirmemailbox.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.confirmemailbox.setObjectName("confirmemailbox")
        self.confirmemailbutton = QtWidgets.QLabel(self.centralwidget)
        self.confirmemailbutton.setEnabled(False)
        self.confirmemailbutton.setGeometry(QtCore.QRect(130, 340, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.confirmemailbutton.setFont(font)
        self.confirmemailbutton.setStyleSheet("background-color:rgb(205, 255, 247)")
        self.confirmemailbutton.setFrameShape(QtWidgets.QFrame.Box)
        self.confirmemailbutton.setTextFormat(QtCore.Qt.AutoText)
        self.confirmemailbutton.setObjectName("confirmemailbutton")
        self.cancelbutton = QtWidgets.QPushButton(self.centralwidget)
        self.cancelbutton.setGeometry(QtCore.QRect(380, 540, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.cancelbutton.setFont(font)
        self.cancelbutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cancelbutton.setStyleSheet("background-color:rgb(255, 55, 41)")
        self.cancelbutton.setObjectName("cancelbutton")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setEnabled(True)
        self.checkBox.setGeometry(QtCore.QRect(130, 470, 131, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.checkBox.setFont(font)
        self.checkBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.checkBox.setStyleSheet("background-color:qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(255, 235, 235, 206), stop:0.35 rgba(255, 188, 188, 80), stop:0.4 rgba(255, 162, 162, 80), stop:0.425 rgba(255, 132, 132, 156), stop:0.44 rgba(252, 128, 128, 80), stop:1 rgba(255, 255, 255, 0))")
        self.checkBox.setObjectName("checkBox")
        self.malebutton = QtWidgets.QRadioButton(self.centralwidget)
        self.malebutton.setEnabled(True)
        self.malebutton.setGeometry(QtCore.QRect(300, 230, 82, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.malebutton.setFont(font)
        self.malebutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.malebutton.setStyleSheet("background-color:qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(255, 235, 235, 206), stop:0.35 rgba(255, 188, 188, 80), stop:0.4 rgba(255, 162, 162, 80), stop:0.425 rgba(255, 132, 132, 156), stop:0.44 rgba(252, 128, 128, 80), stop:1 rgba(255, 255, 255, 0))")
        self.malebutton.setObjectName("malebutton")
        self.femalebutton = QtWidgets.QRadioButton(self.centralwidget)
        self.femalebutton.setGeometry(QtCore.QRect(380, 230, 82, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.femalebutton.setFont(font)
        self.femalebutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.femalebutton.setStyleSheet("background-color:qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(255, 235, 235, 206), stop:0.35 rgba(255, 188, 188, 80), stop:0.4 rgba(255, 162, 162, 80), stop:0.425 rgba(255, 132, 132, 156), stop:0.44 rgba(252, 128, 128, 80), stop:1 rgba(255, 255, 255, 0))")
        self.femalebutton.setObjectName("femalebutton")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(270, 470, 191, 51))
        self.textBrowser.setStyleSheet("background-color:rgb(255, 227, 192)")
        self.textBrowser.setObjectName("textBrowser")
        self.progressBar1 = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar1.setEnabled(False)
        self.progressBar1.setGeometry(QtCore.QRect(470, 390, 118, 16))
        self.progressBar1.setTabletTracking(False)
        self.progressBar1.setProperty("value", 24)
        self.progressBar1.setObjectName("progressBar1")
        self.progressBar2 = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar2.setEnabled(False)
        self.progressBar2.setGeometry(QtCore.QRect(470, 430, 118, 16))
        self.progressBar2.setProperty("value", 24)
        self.progressBar2.setObjectName("progressBar2")
        self.malebutton.raise_()
        self.namebox.raise_()
        self.namebutton.raise_()
        self.userbox.raise_()
        self.createaccountbutton.raise_()
        self.userbutton.raise_()
        self.signupbutton.raise_()
        self.surnamebox.raise_()
        self.surnamebutton.raise_()
        self.genderbutton.raise_()
        self.marriagebox.raise_()
        self.marriagebutton.raise_()
        self.emailbox.raise_()
        self.emailbutton.raise_()
        self.paswoordbox.raise_()
        self.paswoordbutton.raise_()
        self.confirmpaswoordbox.raise_()
        self.confirmpaswoordbutton.raise_()
        self.confirmemailbox.raise_()
        self.confirmemailbutton.raise_()
        self.cancelbutton.raise_()
        self.checkBox.raise_()
        self.textBrowser.raise_()
        self.femalebutton.raise_()
        self.progressBar1.raise_()
        self.progressBar2.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.namebutton.setText(_translate("MainWindow", "Name"))
        self.createaccountbutton.setText(_translate("MainWindow", "CREATE ACCOUNT"))
        self.userbutton.setText(_translate("MainWindow", "Username"))
        self.signupbutton.setText(_translate("MainWindow", "Create My Account"))
        self.surnamebutton.setText(_translate("MainWindow", "Surname"))
        self.genderbutton.setText(_translate("MainWindow", "Gender"))
        self.marriagebutton.setText(_translate("MainWindow", "Marriage Status"))
        self.emailbutton.setText(_translate("MainWindow", "e-mail"))
        self.paswoordbutton.setText(_translate("MainWindow", "Passwoord"))
        self.confirmpaswoordbutton.setText(_translate("MainWindow", "Confirm Passwoord"))
        self.confirmemailbutton.setText(_translate("MainWindow", "Confirm e-mail"))
        self.cancelbutton.setText(_translate("MainWindow", "Cancel"))
        self.checkBox.setText(_translate("MainWindow", "Read and Accepted"))
        self.malebutton.setText(_translate("MainWindow", "Male"))
        self.femalebutton.setText(_translate("MainWindow", "Female"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'sans-serif\'; font-size:8pt; color:#222222; background-color:#ffffff;\">As rights vary by country and jurisdiction, a work may be subject to rights in one country and be in the public domain in another. Some rights depend on registrations on a country-by-country basis, and the absence of registration in a particular country, if required, gives rise to public-domain status for a work in that country. The term public domain may also be interchangeably used with other imprecise or undefined terms such as the &quot;</span><a href=\"https://en.wikipedia.org/wiki/Public_sphere\"><span style=\" font-family:\'sans-serif\'; font-size:8pt; text-decoration: underline; color:#0b0080; background-color:#ffffff;\">public sphere</span></a><span style=\" font-family:\'sans-serif\'; font-size:8pt; color:#222222; background-color:#ffffff;\">&quot; or &quot;</span><a href=\"https://en.wikipedia.org/wiki/Commons\"><span style=\" font-family:\'sans-serif\'; font-size:8pt; text-decoration: underline; color:#0b0080; background-color:#ffffff;\">commons</span></a><span style=\" font-family:\'sans-serif\'; font-size:8pt; color:#222222; background-color:#ffffff;\">&quot;, including concepts such as the &quot;commons of the mind&quot;, the &quot;intellectual commons&quot;, and the &quot;information commons&quot;.</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

